apiVersion: v1
kind: ConfigMap
metadata:
  name: university-registration-config
  namespace: kubedb-monitor-test
  labels:
    app: university-registration
data:
  application.yml: |
    spring:
      profiles:
        active: kubernetes
      datasource:
        url: jdbc:h2:mem:coursedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
        driver-class-name: org.h2.Driver
        username: sa
        password: 
        hikari:
          maximum-pool-size: 30
          minimum-idle: 5
          connection-timeout: 30000
          idle-timeout: 600000
          max-lifetime: 1800000
          
      jpa:
        hibernate:
          ddl-auto: create-drop
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.H2Dialect
            format_sql: true
            generate_statistics: true
            jdbc:
              batch_size: 50
              
      h2:
        console:
          enabled: true
          path: /h2-console
    
    server:
      port: 8080
      
    management:
      endpoints:
        web:
          exposure:
            include: "health,info,metrics,prometheus,env"
      endpoint:
        health:
          show-details: always
          probes:
            enabled: true
      metrics:
        export:
          prometheus:
            enabled: true
            
    app:
      registration:
        initialize-sample-data: true
        data-init-batch-size: 200
        max-concurrent-enrollments: 50
        
    logging:
      level:
        com.university.registration: INFO
        io.kubedb.monitor: DEBUG
        org.hibernate.SQL: INFO
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{40} - %msg%n"