apiVersion: v1
kind: Namespace
metadata:
  name: kubedb-monitor-test
  labels:
    app: kubedb-monitor-test
    version: v1.0.0
    environment: testing
  annotations:
    description: "Namespace for KubeDB Monitor integration testing with university course registration sample app"
    
---
# NetworkPolicy to allow traffic within namespace and from monitoring systems
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kubedb-monitor-test-netpol
  namespace: kubedb-monitor-test
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    - namespaceSelector:
        matchLabels:
          name: kubedb-monitor-system
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - podSelector: {}
  egress:
  - {}  # Allow all egress traffic
  
---
# ResourceQuota for the test namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: kubedb-monitor-test-quota
  namespace: kubedb-monitor-test
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "4"
    pods: "10"
    services: "5"
    secrets: "10"
    configmaps: "10"
    
---
# LimitRange to set default resource limits
apiVersion: v1
kind: LimitRange
metadata:
  name: kubedb-monitor-test-limits
  namespace: kubedb-monitor-test
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container