apiVersion: apps/v1
kind: Deployment
metadata:
  name: university-registration-basic
  namespace: kubedb-monitor-test
  labels:
    app: university-registration-basic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: university-registration-basic
  template:
    metadata:
      labels:
        app: university-registration-basic
      # 주의: KubeDB Monitor 어노테이션이 없음 - 자동 주입되지 않음
    spec:
      containers:
      - name: university-registration
        image: registry.bitgaram.info/kubedb-monitor/university-registration:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        # Spring Boot 기본 설정
        - name: SPRING_PROFILES_ACTIVE
          value: "development"
        # Java 옵션 (KubeDB Agent 없음)
        - name: JAVA_OPTS
          value: "-Xmx256m -Xms128m"
        
        # HikariCP가 인식할 수 있는 올바른 환경변수
        - name: SPRING_DATASOURCE_JDBC_URL
          value: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: "org.h2.Driver"
        - name: SPRING_DATASOURCE_USERNAME
          value: "sa"
        - name: SPRING_DATASOURCE_PASSWORD
          value: ""
        
        # HikariCP 명시적 설정
        - name: SPRING_DATASOURCE_HIKARI_JDBC_URL
          value: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
        - name: SPRING_DATASOURCE_HIKARI_DRIVER_CLASS_NAME
          value: "org.h2.Driver"
        - name: SPRING_DATASOURCE_HIKARI_USERNAME
          value: "sa"
        - name: SPRING_DATASOURCE_HIKARI_PASSWORD
          value: ""
        - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
          value: "5"
        - name: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
          value: "1"
        - name: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
          value: "20000"
        
        # JPA/Hibernate 설정
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "create-drop"
        - name: SPRING_JPA_SHOW_SQL
          value: "false"
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.H2Dialect"
        
        # H2 콘솔 비활성화
        - name: SPRING_H2_CONSOLE_ENABLED
          value: "false"
        
        # 데이터 초기화 비활성화
        - name: APP_REGISTRATION_INITIALIZE_SAMPLE_DATA
          value: "false"
        
        # 로깅 최소화
        - name: LOGGING_LEVEL_ROOT
          value: "WARN"
        - name: LOGGING_LEVEL_COM_UNIVERSITY_REGISTRATION
          value: "INFO"
        - name: LOGGING_PATTERN_CONSOLE
          value: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        
        # Health check 설정
        livenessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
      
      imagePullSecrets:
      - name: registry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: university-registration-basic-service
  namespace: kubedb-monitor-test
  labels:
    app: university-registration-basic
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: university-registration-basic