apiVersion: apps/v1
kind: Deployment
metadata:
  name: university-registration-monitored
  namespace: kubedb-monitor-test
  labels:
    app: university-registration-monitored
spec:
  replicas: 1
  selector:
    matchLabels:
      app: university-registration-monitored
  template:
    metadata:
      labels:
        app: university-registration-monitored
      annotations:
        # KubeDB Monitor 활성화
        kubedb.monitor/enable: "true"
        kubedb.monitor/db-types: "h2"
        kubedb.monitor/sampling-rate: "1.0"
        kubedb.monitor/slow-query-threshold: "100"
        kubedb.monitor/collector-type: "logging"
    spec:
      initContainers:
      - name: kubedb-agent-init
        image: registry.bitgaram.info/kubedb-monitor/agent:latest
        command: ["sh", "-c"]
        args: ["cp /opt/kubedb-monitor-agent.jar /opt/kubedb-agent/"]
        volumeMounts:
        - name: kubedb-agent
          mountPath: /opt/kubedb-agent
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      containers:
      - name: university-registration
        image: registry.bitgaram.info/kubedb-monitor/university-registration:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        # Spring Boot 기본 설정
        - name: SPRING_PROFILES_ACTIVE
          value: "development"
        # Java 옵션과 KubeDB Agent
        - name: JAVA_OPTS
          value: "-Xmx512m -Xms256m -XX:+UseG1GC -javaagent:/opt/kubedb-agent/kubedb-monitor-agent.jar=db-types=h2,sampling-rate=1.0,slow-query-threshold=100,collector-type=logging"
        # HikariCP가 인식할 수 있는 올바른 환경변수
        - name: SPRING_DATASOURCE_JDBC_URL
          value: "jdbc:h2:mem:coursedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:h2:mem:coursedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL"
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: "org.h2.Driver"
        - name: SPRING_DATASOURCE_USERNAME
          value: "sa"
        - name: SPRING_DATASOURCE_PASSWORD
          value: ""
        # HikariCP 명시적 설정
        - name: SPRING_DATASOURCE_HIKARI_JDBC_URL
          value: "jdbc:h2:mem:coursedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL"
        - name: SPRING_DATASOURCE_HIKARI_DRIVER_CLASS_NAME
          value: "org.h2.Driver"
        - name: SPRING_DATASOURCE_HIKARI_USERNAME
          value: "sa"
        - name: SPRING_DATASOURCE_HIKARI_PASSWORD
          value: ""
        - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
          value: "10"
        - name: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
          value: "2"
        - name: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
          value: "30000"
        # JPA/Hibernate 안전 설정
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "create-drop"
        - name: SPRING_JPA_SHOW_SQL
          value: "false"
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.H2Dialect"
        # H2 콘솔 활성화 (데모를 위해)
        - name: SPRING_H2_CONSOLE_ENABLED
          value: "true"
        - name: SPRING_H2_CONSOLE_PATH
          value: "/h2-console"
        # 데이터 초기화 활성화 (데모를 위해)
        - name: APP_REGISTRATION_INITIALIZE_SAMPLE_DATA
          value: "true"
        # 로깅 설정
        - name: LOGGING_LEVEL_ROOT
          value: "INFO"
        - name: LOGGING_LEVEL_COM_UNIVERSITY_REGISTRATION
          value: "DEBUG"
        - name: LOGGING_LEVEL_IO_KUBEDB_MONITOR
          value: "DEBUG"
        - name: LOGGING_PATTERN_CONSOLE
          value: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"
        volumeMounts:
        - name: kubedb-agent
          mountPath: /opt/kubedb-agent
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 240
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 8
      volumes:
      - name: kubedb-agent
        emptyDir: {}
      imagePullSecrets:
      - name: registry-secret