apiVersion: apps/v1
kind: Deployment
metadata:
  name: university-registration-minimal
  namespace: kubedb-monitor-test
  labels:
    app: university-registration-minimal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: university-registration-minimal
  template:
    metadata:
      labels:
        app: university-registration-minimal
    spec:
      containers:
      - name: university-registration
        image: registry.bitgaram.info/kubedb-monitor/university-registration:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        # Spring Boot 기본 설정
        - name: SPRING_PROFILES_ACTIVE
          value: "development"
        # Java 옵션
        - name: JAVA_OPTS
          value: "-Xmx256m -Xms128m"
        # H2 데이터베이스 가장 간단한 설정
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:h2:mem:testdb"
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: "org.h2.Driver"
        - name: SPRING_DATASOURCE_USERNAME
          value: "sa"
        - name: SPRING_DATASOURCE_PASSWORD
          value: ""
        # JPA/Hibernate 가장 안전한 설정
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "create-drop"
        - name: SPRING_JPA_SHOW_SQL
          value: "false"
        # H2 콘솔 비활성화
        - name: SPRING_H2_CONSOLE_ENABLED
          value: "false"
        # 데이터 초기화 완전 비활성화
        - name: APP_REGISTRATION_INITIALIZE_SAMPLE_DATA
          value: "false"
        # 로깅 최소화
        - name: LOGGING_LEVEL_ROOT
          value: "WARN"
        - name: LOGGING_LEVEL_COM_UNIVERSITY_REGISTRATION
          value: "INFO"
        - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK
          value: "WARN"
        - name: LOGGING_LEVEL_ORG_HIBERNATE
          value: "WARN"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 10
      imagePullSecrets:
      - name: registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: university-registration-minimal-service
  namespace: kubedb-monitor-test
  labels:
    app: university-registration-minimal
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: university-registration-minimal